KEYWORDS = {
    "if", "else", "elif", "while", "for", "return", "def", "class",
    "import", "from", "as", "in", "not", "and", "or", "lambda",
    "pass", "break", "continue", "yield", "raise", "try", "except",
    "finally", "with", "is", "None", "True", "False", "del",
    "global", "nonlocal", "assert", "async", "await", "match", "case", "type"
}

MULTI_CHAR_OPERATORS = {
    "//=": "FLOORDIV_ASSIGN",
    "**=": "POW_ASSIGN",
    "<<=": "LSHIFT_ASSIGN",
    ">>=": "RSHIFT_ASSIGN",
    "+=":  "PLUS_ASSIGN",
    "-=":  "MINUS_ASSIGN",
    "*=":  "TIMES_ASSIGN",
    "/=":  "SLASH_ASSIGN",
    "%=":  "MOD_ASSIGN",
    "&=":  "AND_ASSIGN",
    "|=":  "OR_ASSIGN",
    "^=":  "XOR_ASSIGN",
    "@=":  "AT_ASSIGN",
    "==":  "EQ",
    "!=":  "NEQ",
    "<=":  "LE",
    ">=":  "GE",
    "->":  "ARROW",
    ":=":  "WALRUS",
    "//":  "FLOORDIV",
    "**":  "POW",
    "<<":  "LSHIFT",
    ">>":  "RSHIFT",
    "...": "ELLIPSIS",
}

SINGLE_CHAR_OPERATORS = {
    "+": "PLUS",
    "-": "MINUS",
    "*": "TIMES",
    "/": "SLASH",
    "%": "MOD",
    "=": "ASSIGN",
    "<": "LT",
    ">": "GT",
    "&": "BITAND",
    "|": "BITOR",
    "^": "BITXOR",
    "~": "BITNOT",
    "@": "AT",
    "(": "LPAREN",
    ")": "RPAREN",
    "[": "LBRACKET",
    "]": "RBRACKET",
    "{": "LBRACE",
    "}": "RBRACE",
    ",": "COMMA",
    ".": "DOT",
    ":": "COLON",
    ";": "SEMICOLON",
}